import { Content } from '@/components/content/Content';
import { Header } from '@/components/header/Header';
import { SettingsMap } from '@/components/settings-map/SettingsMap';
import { useInitRequest } from '@/hooks/useInitRequest';
import useWindowDimensions from '@/hooks/useWindowDimensions';
import { RootState } from '@/store/store';
import { actions as userMapAction } from '@/store/user-map/userMap.slice';
import { actions as viewSettingsActions } from '@/store/view-settings/viewSettings.slice';
import Head from 'next/head';
import { useSearchParams } from 'next/navigation';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';

export default function Home({data, maps}:any) {
	console.log(maps.map)
  const dispatch = useDispatch();
	const adresFilterString = useSelector(
		(state: RootState) => state.adresFilterString,
	);
	const { isSettingsMap } = useSelector(
		(state: RootState) => state.viewSettings,
	);
	const { width } = useWindowDimensions();
	const { push } = useRouter();
	const searchParams = useSearchParams();
	const map = searchParams.get('map');
	const { getObject, getFilters } = useInitRequest();
	const [initApp, setInitApp] = useState(false);

	useEffect(() => {
		dispatch(userMapAction.addNumMap(map));
	}, []);

	useEffect(() => {
		if (adresFilterString.srcRequest !== '') {
			setInitApp(true);
		}
	}, [adresFilterString.srcRequest]);

	useEffect(() => {
		if (!map) {
			push(`?map=7`);
		} else {
			getObject();
			getFilters();
		}
	}, [map, initApp]);

	useEffect(() => {
		if (width && width <= 767.98) {
			dispatch(viewSettingsActions.defaultFilters(''));
			dispatch(viewSettingsActions.defaultObjects(''));
		}
	}, [width]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header data={data}/>
			<div style={{ height: '100%' }}>
			<Content data={data} />
			{isSettingsMap && <SettingsMap data={data} />}
		</div>
		</>
	);
}

export const getServerSideProps = async ({ query }:any) => {
	console.log(query.map)
if (query.map) {
	const response = await fetch(`https://app.mosmap.ru/api/get_objects.php?map=${query.map}`);
	const data = await response.json()
	
	return {
		props: {
			data,
			maps: query
		}
	}
} else {
	const response = await fetch(`https://app.mosmap.ru/api/get_objects.php?map=7`);
	const data = await response.json()

	return {
		props: {
			data,
			maps: query
		}
	}

}
}